MODEL:
  TYPE: retinanet
  CONV_BODY: FPN.add_fpn_ResNet50_conv5_body
  NUM_CLASSES: 8
NUM_GPUS: 2
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.001
  GAMMA: 0.1
  MAX_ITER: 150000
  STEPS: [0, 30000, 60000, 90000]   #[0, 60000, 80000]
FPN:
  FPN_ON: True
  MULTILEVEL_RPN: True
  RPN_MAX_LEVEL: 6  #7
  RPN_MIN_LEVEL: 2  #3
  COARSEST_STRIDE: 64   #128=2^7
  EXTRA_CONV_LEVELS: True
RETINANET:
  RETINANET_ON: True
  NUM_CONVS: 2  #4
  ASPECT_RATIOS: (1.0, 2.0, 3.0, 5.0, 0.2, 0.5) #(1.0, 2.0, 0.5)
  SCALES_PER_OCTAVE: 4  #3
  ANCHOR_SCALE: 4
  LOSS_GAMMA: 2.0
  LOSS_ALPHA: 0.25
TRAIN:
  WEIGHTS: /opt/zhangjing/Detectron/resnet50_model_final.pkl  #https://s3-us-west-2.amazonaws.com/detectron/ImageNetPretrained/MSRA/R-50.pkl
  DATASETS: ('voc_2007_train',)  #, 'coco_2007_val')
  SCALES: (1080,)
  MAX_SIZE: 1920
  RPN_STRADDLE_THRESH: -1  # default 0
TEST:
  DATASETS: ('coco_2007_val',)
  SCALE: 1080
  MAX_SIZE: 1920
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 10000   # Per FPN level
  RPN_POST_NMS_TOP_N: 2000
OUTPUT_DIR: .
