MODEL:
  TYPE: retinanet
  CONV_BODY: FPN.add_fpn_ResNet101_conv5_body
  NUM_CLASSES: 8
NUM_GPUS: 2
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.001
  GAMMA: 0.1
  MAX_ITER: 150000
  STEPS: [0, 50000, 100000]
FPN:
  FPN_ON: True
  MULTILEVEL_RPN: True
  RPN_MAX_LEVEL: 4
  RPN_MIN_LEVEL: 2
  COARSEST_STRIDE: 16
  EXTRA_CONV_LEVELS: True
RETINANET:
  RETINANET_ON: True
  NUM_CONVS: 1
  ASPECT_RATIOS: (1.0,2.0,0.5)
  SCALES_PER_OCTAVE: 3
  ANCHOR_SCALE: 4
  LOSS_GAMMA: 2.0
  LOSS_ALPHA: 0.25
TRAIN:
  WEIGHTS: /opt/ligang/detectron/Detectron-master/models/model_final.pkl
  DATASETS: ('coco_2007_class8_pic812_train',)
  SCALES: (1080,)
  MAX_SIZE: 1920
  RPN_STRADDLE_THRESH: -1  # default 0
TEST:
  DATASETS: ('coco_2007_class8_pic202_val',) # coco_small_build_benchmark349 coco_2007_val coco_20_build   coco_2007_class13_pic250_val  
  SCALE: 1080
  MAX_SIZE: 1920
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 10000  # Per FPN level
  RPN_POST_NMS_TOP_N: 2000
OUTPUT_DIR: .
